version: '3'

services:
  flask_backend:
    container_name: flask_backend_container
    restart: always
    image: flask
    build: ./app/backend
    volumes:
      - ./app/backend:/usr/src/app/backend
    depends_on:
      - database
    env_file:
     - .env

  database:
    container_name: database_container
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  db_data:
